apiVersion: delivery.ocm.software/v1alpha1
kind: ComponentSubscription
metadata:
  name: podinfo-transfer
  namespace: ocm-system
spec:
  source:
    url: ghcr.io/mohammad-ammar14  
    secretRef:
      name: creds
  destination:
    url: podinfo-component.int.repositories.cloud.sap
    secretRef:
      name: acreds
  component: github.com/ammar/que
  interval: 1m0s
  semver: v1.0.0
  # verify:
  #   - signature:
  #       name: alice
  #       key:
  #         name: alice-publickey
status:
  latestVersion: v1.0.0
  replicatedVersion: v1.0.0