apiVersion: delivery.ocm.software/v1alpha1
kind: ComponentSubscription
metadata:
  name: podinfo-transfer-sap-art
  namespace: ocm-system
spec:
  source:
    url: ghcr.io/mohammad-ammar14  
    secretRef:
      name: regcred
  destination:
    url: artefact-transfer-test.int.repositories.cloud.sap
    secretRef:
      name: acreds
  component: github.com/ammar/que
  interval: 10m0s
  semver: v1.0.0
  # verify:
  #   - signature:
  #       name: alice
  #       key:
  #         name: alice-publickey
status:
  latestVersion: v1.0.1
  replicatedVersion: v1.0.0