apiVersion: delivery.ocm.software/v1alpha1
kind: ComponentSubscription
metadata:
  name: podify-subscription-test
  namespace: ocm-system
spec:
  interval: 10m
  component: github.com/sidhishruti22/podify
  semver: "=>v1.0.0"
  source:
    url: ghcr.io/sidhishruti22
    secretRef:
      name: creds
  destination:
    url: ghcr.io/mohammad-ammar14
    secretRef:
      name: creds