apiVersion: delivery.ocm.software/v1alpha1
kind: ComponentSubscription
metadata:
  name: podinf
  namespace: ocm-system
spec:
  source:
    secretRef:
      name: regcred
    url: ghcr.io/mohammad-ammar14
  destination:
    secretRef:
      name: sregcred
    url: ghcr.io/sidhishruti22
  component: github.com/ammar/que
  interval: 10m0s
  semver: v1.0.0
  verify:
    - signature:
        name: alice
        key:
          name: alice-publickey
status:
  latestVersion: v1.0.0
  replicatedVersion: v1.0.0