apiVersion: delivery.ocm.software/v1alpha1
kind: ComponentSubscription
metadata:
  name: podify-subscription-predemo-test
  namespace: ocm-system
spec:
  interval: 10m
  component: github.com/sidhishruti22/podify_test
  semver: "=>v1.0.1"
  source:
    url: ghcr.io/sidhishruti22
    secretRef:
      name: creds
  destination:
    url: artefact-transfer-test.int.repositories.cloud.sap
    secretRef:
      name: acreds
      