apiVersion: delivery.ocm.software/v1alpha1
kind: ComponentSubscription
metadata:
  name: podify-subscription-test-4
  namespace: ocm-system
spec:
  interval: 10m
  component: github.com/ammar/que
  semver: "=>v1.0.0"
  source:
    url: ghcr.io/mohammad-ammar14
    secretRef:
      name: creds
  destination:
    url: artefact-transfer-test.int.repositories.cloud.sap
    secretRef:
      name: acreds