apiVersion: delivery.ocm.software/v1alpha1
kind: ComponentSubscription
metadata:
  name: podify-subscription-test
  namespace: ocm-system
spec:
  interval: 10m
  component: github.com/sidhishruti22/podify
  semver: "=>v1.0.0"
  source:
    url: ghcr.io/sidhishruti22
    secretRef:
      name: acreds
  destination:
    url: artefact-transfer-test.int.repositories.cloud.sap
    secretRef:
      name: creds