apiVersion: delivery.ocm.software/v1alpha1
kind: ComponentSubscription
metadata:
  name: podify-subscription-test-4
  namespace: ocm-system
spec:
  source:
    secretRef:
      name: creds
    url: ghcr.io/sidhishruti22
  destination:
    secretRef:
      name: creds
    url: ghcr.io/mohammad-ammar14
  component: github.com/sidhishruti22/podify
  interval: 10s
  semver: "=>v1.0.0"
  # verify:
  #   - name: phoban01
  #     publicKey:
  #       secretRef:
  #         name: phoban01-publickey
