apiVersion: delivery.ocm.software/v1alpha1
kind: ComponentSubscription
metadata:
  name: podinfo
  namespace: ocm-system
spec:
  source:
    url: ghcr.io/mohammad-ammar14  
    secretRef:
      name: creds
  destination:
    url: ghcr.io/sidhishruti22  
    secretRef:
      name: sregcred
  component: github.com/ammar/que
  interval: 1m0s
  semver: v1.0.1
  # verify:
  #   - signature:
  #       name: alice
  #       key:
  #         name: alice-publickey
status:
  latestVersion: v1.0.1
  replicatedVersion: v1.0.1