apiVersion: delivery.ocm.software/v1alpha1
kind: ComponentSubscription
metadata:
  name: podify-subscription-test-2
  namespace: ocm-system
spec:
  source:
    secretRef:
      name: creds
    url: ghcr.io/mohammad-ammar14
  destination:
    secretRef:
      name: screds
    url: ghcr.io/sidhishruti22
  component: github.com/acme/db-app
  interval: 10s
  semver: "=>v1.0.0"
  # verify:
  #   - name: phoban01
  #     publicKey:
  #       secretRef:
  #         name: phoban01-publickey
