apiVersion: delivery.ocm.software/v1alpha1
kind: ComponentSubscription
metadata:
  name: podinf
  namespace: ocm-system
spec:
  source:
    secretRef:
      name: creds
    url: ghcr.io/mohammad-ammar14
  destination:
    secretRef:
      name: screds
    url: ghcr.io/sidhishruti22
  component: github.com/ammar/que
  interval: 1m0s
  semver: v1.0.0
  # verify:
  #   - signature:
  #       name: alice
  #       key:
  #         name: alice-publickey
status:
  latestVersion: v1.0.0
  replicatedVersion: v1.0.0